# DecayEvent.py generated by R. Yokoyama on 10/04/2018
from Nuclide import Nuclide

class DecayEvent(Nuclide):
    # container class for a decay event
    def __init__(self, nuclide):
        self.z = nuclide.z
        self.n = nuclide.n
        self.time = 0
        self.n_neutron = 0 # number of neutron emitted
