# Nuclide.py generated by R. Yokoyama on 10/04/2018

class Nuclide(object):
    # base class for a nuclide (Z,N)
    def __init__(self):
        self.z = 0
        self.n = 0

class NuclideProperty(Nuclide):
    # container of the decay properties of a nuclide
    # read from database
    def __init__(self):
        self.pn = []
        self.halflife = 0.

class NuclidePopulation(Nuclide):
    # container of the population of a nuclide
    def __init__(self):
        self.counts = 0
