# PopulationGIFMaker.py generated by R. Yokoyama on 10/05/2018
from PopulationPlotter import PopulationPlotter
from ROOT import gStyle
from ROOT import gPad
import os

class PopulationGIFMaker(object):
    # A class to make a gif animation of nuclear population
    # from a given list of decay chains
    def __init__(self):
        self.plotter = PopulationPlotter()
        self.time_list = []

    def configure(self, config):
        # initialize variables by a given yaml node
        self.plotter.configure(config['PopulationPlotter'])
        self.time_list = config['TimeList'] # a list of time to make the animation
        self.img_name = config['ImgName'] # a prefix of the image file names
        self.convert_cmd = config['ConvertCommand'] # "convert -layers optimize -loop 0 -delay xx" for example
        self.convert_cmd_last = config['ConvertCommandLast'] # put "-delay xx" if you want to make the last image longer
        gStyle.SetPalette(config['PaletteId']) # ROOT palette ID

    def MakeGIFImage(self, decay_list):
        # print the population images at the times which are specified
        # in the self.time_list
        gStyle.SetOptStat(0)
        for (i,time) in enumerate(self.time_list):
            hist = self.plotter.plotPopulation(decay_list,time)
            hist.SetName("population"+str(i))
            hist.SetTitle("Population at t = "+str(time)+"sec")
            hist.GetXaxis().SetTitle("N")
            hist.GetYaxis().SetTitle("Z")
            hist.Draw("colz")
            gPad.SetLogz()
            gPad.Print(self.img_name + "_%02d.png" % i)
        gPad.Print(self.img_name + "_last.png")

    def MakeGIF(self):
        # generates .gif file using "convert" command
        cmd = self.convert_cmd + " " + self.img_name + "_*.png " \
              + self.convert_cmd_last + " " + self.img_name \
              + "_last.png " + self.img_name + ".gif"
        os.system(cmd) 
