# PopulationGIFMaker.py generated by R. Yokoyama on 10/05/2018
from PopulationPlotter import PopulationPlotter
import ROOT
import os

class PopulationGIFMaker(object):
    # A class to make a gif animation of nuclear population
    # from a given list of decay chains
    def __init__(self):
        self.plotter = PopulationPlotter()
        self.time_list = []
        self.log_y = False

    def configure(self, config):
        # initialize variables by a given yaml node
        self.plotter.configure(config['PopulationPlotter'])
        self.time_list = config['TimeList'] # a list of time to make the animation
        self.img_name = config['ImgName'] # a prefix of the image file names
        self.convert_cmd = config['ConvertCommand'] # "convert -layers optimize -loop 0 -delay xx" for example
        self.convert_cmd_last = config['ConvertCommandLast'] # put "-delay xx" if you want to make the last image longer
        self.log_y = bool(config['Logy']) # Log scale on Y axis
        ROOT.gStyle.SetPalette(config['PaletteId']) # ROOT palette ID

    def MakeGIFImage(self, decay_list):
        # print the population images at the times which are specified
        # in the self.time_list
        ROOT.gStyle.SetOptStat(0)
        for (i,time) in enumerate(self.time_list):
            hist = self.plotter.plotPopulation(decay_list,time)
            hist.SetName("population"+str(i))
            hist.SetTitle("Population at t = "+str(time)+"sec")
            hist.GetXaxis().SetTitle("N")
            hist.GetYaxis().SetTitle("Z")
            hist.Draw("colz")
            ROOT.gPad.SetLogz()
            ROOT.gPad.Print(self.img_name + "_%02d.png" % i)
        ROOT.gPad.Print(self.img_name + "_last.png")

    def Make1DGIFImage(self, decay_list1, decay_list2, name1, name2):
        # print the population images at the times which are specified
        # in the self.time_list
        ROOT.gStyle.SetOptStat(0)
        canv = ROOT.TCanvas("population","population",1200,1920)
            
        for (i,time) in enumerate(self.time_list):
            hists1 = self.plotter.plotPopulation1D(decay_list1,time)
            canv.Clear()
            canv.Divide(1,len(hists1))
            label = ROOT.TText()
            label.SetTextColor(2)
            label.SetTextAlign(13)
            label.SetTextSize(0.3)
            label.SetNDC(1)
            j = 0
            for key in hists1:
                j = j+1
                pad = canv.cd(j)
                if self.log_y:
                    pad.SetLogy()
                    hists1[key].SetMinimum(1)
                hists1[key].SetName("population"+str(i)+"_"+str(key)+name1)
                hists1[key].SetTitle("Population at t = "+str(time)+"sec, z = "+str(key)+" "+name1)
                hists1[key].GetXaxis().SetTitle("N")
                hists1[key].GetYaxis().SetTitle("counts")
                hists1[key].SetLineColor(2)
                hists1[key].Draw()
            hists2 = self.plotter.plotPopulation1D(decay_list2,time)
            j = 0
            for key in hists2:
                j = j+1
                pad = canv.cd(j)
                if self.log_y:
                    hists2[key].SetMinimum(1)
                hists2[key].SetName("population"+str(i)+"_"+str(key)+name2)
                hists2[key].SetTitle("Population at t = "+str(time)+"sec, z = "+str(key)+" "+name2)
                hists2[key].GetXaxis().SetTitle("N")
                hists2[key].GetYaxis().SetTitle("counts")
                hists2[key].SetLineColor(4)
                hists2[key].Draw("same")
                label.DrawText(0,1,"z = "+str(key))
            canv.cd(1)
            label.SetTextAlign(33)
            label.DrawText(1,1,"t = "+str(time)+"sec")
            label.SetTextAlign(31)
            label.DrawText(1,0.5,"red:beoh")
            label.SetTextColor(4)
            label.SetTextAlign(33)
            label.DrawText(1,0.5,"blue:old")
            canv.Print(self.img_name + "_%02d.png" % i)
        canv.Print(self.img_name + "_last.png")

    def MakeGIF(self):
        # generates .gif file using "convert" command
        cmd = self.convert_cmd + " " + self.img_name + "_*.png " \
              + self.convert_cmd_last + " " + self.img_name \
              + "_last.png " + self.img_name + ".gif"
        os.system(cmd) 
