DBFile: "db/nuclei.db"
#DBTable: "frdm_beoh"
#OutputFile: frdm_beoh.root
DBTable: "frdm_old"
OutputFile: frdm_old.root

EventPlotter:
    n_decay:
        nbins: 100
        low: 0.
        up: 100.
    decay_activity:
        nbins: 10000
        low: 0.
        up: 1.E+3
    n_ave:
        nbins: 100
        low: 0.
        up: 100.

DecaySimulator:
    StdOutPrint: True
#    StdOutPrint: False

PopulationPlotter:
    low_n: 30
    up_n: 80
    low_z: 20
    up_z: 50
